# Generated by Django 4.0.5 on 2022-06-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_conversion_remove_converter_file_remove_upload_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversion',
        ),
        migrations.AddField(
            model_name='converter',
            name='token',
            field=models.TextField(default=None, help_text='Enter your token.', max_length=36),
        ),
    ]
